services:
  - type: web
    name: school-management-system
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    dockerContext: ./school_mgmt_enterprise
    dockerfilePath: ./school_mgmt_enterprise/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString

databases:
  - name: school-db
    plan: free
